server:
    port: 8080

spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: postgres://bsdeyrkazrmoft:0a1401a1ebcbcbfe40adbb126ee5f8f2319cd26276d6ddb463809499e9b1730b@ec2-54-221-217-158.compute-1.amazonaws.com:5432/d25aucuairch14
        databaseName: d25aucuairch14
        serverName: ec2-54-221-217-158.compute-1.amazonaws.com
        username: bsdeyrkazrmoft
        password: 0a1401a1ebcbcbfe40adbb126ee5f8f2319cd26276d6ddb463809499e9b1730b

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: hipcontacts

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
